name: deploy
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: setup wiretguard
      uses: Anillc/setup-wireguard@v2
      with:
        endpoint: ${{ secrets.WG_ENDPOINT }}
        endpoint_public_key: NQfs6evQLemuJcdcvpO4ds1wXwUHTlzlQXWTJv+WCXY=
        ips: 10.127.20.114/32
        allowed_ips: 0.0.0.0/0, ::/0
        private_key: ${{ secrets.WG_PRIVATE_KEY }}
    - name: setup network
      run: |
        sudo apt install -y iproute2
        sudo tee /etc/resolv.conf <<EOF
        nameserver 172.20.0.53
        nameserver 172.23.0.53
        EOF
        sudo ip route add 172.16.0.0/12 dev deploy
        sudo ip route add 10.0.0.0/8 dev deploy
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: anillc
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - uses: shimataro/ssh-key-action@v2
      with:
        key: '${{ secrets.DEPLOY_KEY }}'
        known_hosts: unnecessary
    - name: deploy
      run: |
        nix develop -c deploy -s